services:
  supportbot:
    build: .
    restart: unless-stopped
    volumes:
      - ./config:/bot/config
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/support

  mongodb:
    image: mongo:8.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./.tmp/mongodb_data:/data/db 

  signal-cli:
    image: bbernhard/signal-cli-rest-api:latest
    platform: linux/amd64
    environment:
      - MODE=native #supported modes: json-rpc, native, normal
      #- AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
    ports:
      - "40153:8080"
    volumes:
      - signal:/home/.local/share/signal-cli

  # mongodb web interface
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password  

volumes:
  mongodb_data:
  signal:
