# bot settings
bot_token: 'ENV' # support bot token
staffchat_id: 'ENV' # eg. -123456789
staffchat_type: 'telegram'
staffchat_parse_mode: 'MarkdownV2'
owner_id: 'ENV'

spam_cant_msg: 5
spam_time: 300000 # time (in MS) in which user may send 5 messages

# example for custom connection to mongodb from config file (up from 4.2.2 version), uncomment if you don't using docker environments.
mongodb_uri: 'ENV'

parse_mode: 'Markdown' # Experimental. Do not change unless you know what you are doing. Options: Markdown/MarkdownV2/HTML
allow_private: false # Allow / disallow option for staff to chat privately
direct_reply: false # Set this to true to just forward staff users to a user chat when allow_private
auto_close_tickets: true # Close tickets after answering
anonymous_tickets: true # Include userid in tickets or not
anonymous_replies: true # Include staff member name in response
show_auto_replied: false # Send auto replied msgs to staff chat
show_user_ticket: false # Show ticket id to user
autoreply_confirmation: true # Reply with language.confirmationMessage on each incoming message
clean_replies: false # Remove footer and header from response
pass_start: false # Pass /start command to support directly

signal_enabled: false # Enable/disable signal
signal_number: '+12345689' # Your signal number / account
signal_host: 'localhost:40153' # Signal host (default: localhost:40153)

web_server: false # Enable/disable web server
web_server_port: 8080 # Port for web server

dev_mode: false # Enable/disable dev mode

# customize your language
language:
  startCommandText: "Добро пожаловать в наш чат поддержки! Можете задавать вопрос"
  faqCommandText: "Получить этого бота: github.com (https://github.com/bostrot/telegram-support-bot)"
  helpCommandText: "*Доступные команды:* /help /id"
  helpCommandStaffText: "*Доступные команды:*\n
    /start - Небольшое введение \n
    /faq - Показать часто задаваемые вопросы \n
    /open - *Staff* Показывает список открытых тикетов \n
    /reopen - *Staff* Переоткрыть закрытый тикет \n
    /close - *Staff* Ответить в тикете этой командой, чтобы закрыть и разбанить \n
    /clear - *Staff* Закрывает все тикеты \n
    /ban - *Staff* Заблокировать пользователя в чате \n
    /unban - *Staff* Разблокировать пользователя"
  confirmationMessage: "Спасибо за обращение. Мы ответим как можно скорее."
  blockedSpam: "Вы отправили слишком много вопросов за последнее время. Пожалуйста, успокойтесь и подождите, пока сотрудники не рассмотрят их."
  ticket: "Тикет"
  closed: "закрыт"
  acceptedBy: "был принят"
  dear: "Привет"
  regards: "С уважением,"
  from: "от"
  language: "Язык"
  msg_sent: "Сообщение отправлено пользователю"
  file_sent: "Файл отправлен пользователю"
  usr_with_ticket: "Пользователь с тикетом"
  banned: "забанен"
  replyPrivate: "Ответить в приват"
  services: "Выберите услугу из списка ниже"
  customer: "клиент"
  msgForwarding: "Ваши сообщения теперь будут пересылаться поставщикам группы: "
  back: "Назад"
  whatSubCategory: "Какая подкатегория лучше всего описывает ваши потребности?"
  prvChatEnded: "Приватный чат завершён."
  prvChatOpened: "Открыт приватный чат с клиентом."
  prvChatEnd: "Завершить приватный чат"
  prvChatOpenedCustomer: "Открыт приватный чат"
  instructionsSent: "Инструкции были отправлены вам в личные сообщения."
  openTickets: "Открытые тикеты"
  support: "Поддержка"
  prvChatOnly: "Эту команду можно использовать только в приватном чате."
  ticketClosed: "Ваш тикет был закрыт нашими сотрудниками. Вы можете открыть новый тикет в любое время."
  links: "Прямые ссылки поддержки"
  textFirst: "Пожалуйста, отправьте нам сообщение перед отправкой изображения, чтобы мы могли лучше вам помочь."
  ticketClosedError: "Вы не можете отвечать на закрытый тикет."
  automatedReply: "Это автоматический ответ."
  automatedReplyAuthor: "MineBridge."
  doesntHelp: "Это не помогает."
  automatedReplySent: "Автоматический ответ был отправлен пользователю."
  ticketReopened: "Тикет был повторно открыт."
  regardsGroup: "MineBridge"

autoreply:
  # - question: "install"
  #   answer: "Если вы хотите установить бота, вы можете воспользоваться следующей ссылкой: \
  #     Getting Started (https://github.com/bostrot/telegram-support-bot/wiki/Getting-started)  \
  #     Также вы можете воспользоваться нашим сервисом одного клика для установки и хостинга: \
  #     [Botspace](https://botspace.bostrot.com/)"
  - question: "Уверен?"
    answer: "Да."
# categories:
#  - name: "Category1"
#    subgroups:
#    - name: "Sub1"
#      group_id: "-12345678910"
#    - name: "Sub2"
#      group_id: "-12345678910"
#    - name: "Sub3"
#      group_id: "-12345678910"
#  - name: "Category2"
#    subgroups:
#    - name: "Sub4"
#      group_id: "-12345678910"
#    - name: "Sub5"
#      group_id: "-12345678910"
#    - name: "Sub6"
#      group_id: "-12345678910"
#  - name: "Category with no subcategories"
#    group_id: "-12345678910"
#  - name: "Admin Chat"
#    group_id: "-12345678910"
#  - name: "Other issues"
#    tag: "#other"
#    msg: "Please specify your order number and describe the problem in as much detail as possible"
#    group_id: "-12345678910"
#  - name: "Contact"
#    msg: "Check out our Website"

use_llm: false # Will enable show_auto_replied when set to true
llm_api_key: 'API_KEY'
llm_base_url: 'https://api.openai.com/v1'
llm_model: 'qwen-2.5-7b-instruct'
llm_knowledge: >
    Q: What is Botspace?
    A: Botspace is a cloud-based project management tool designed for teams to collaborate, track tasks, and manage workflows efficiently.

    Q: What platforms are supported?
    A: Web, iOS, and Android.

    Q: How can I reset my password?
    A: Go to the login page, click "Forgot Password", enter your email, and follow the instructions.

    Q: Where can I update my billing information?
    A: Go to Settings > Billing and click "Update Payment Method".

    Q: Do you offer refunds?
    A: We offer refunds within 14 days of purchase. (tell the user that a member of the team will reach out to them)

    Q: Can I download my invoices?
    A: Yes. In Settings > Billing > Invoices, click "Download PDF".

    Q: How do I delete my account?
    A: Go to Settings > Account, scroll down, and click "Delete Account". This action is irreversible.

    Q: Can I change my email address?
    A: Yes, under Settings > Profile, edit your email and confirm it via the verification link sent.

    Q: How do I invite team members?
    A: Go to Team Settings > Invite Member, enter the email, and assign a role.

    Q: What are the available roles?
    A: Admin, Manager, and Member. Admins have full access; Managers can edit projects; Members have view-only access.

    Q: Do you offer an API?
    A: Yes, documentation is at: https://api.productname.com/docs

    Q: What's the uptime guarantee?
    A: 99.9% SLA for paid plans.
